name: hva_news_app
description: HVA News App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.2.0
  flutter_html: ^3.0.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.3.0
  photo_view: ^0.15.0
  youtube_player_flutter: ^9.0.1
  image_picker: ^1.1.2
  webview_flutter: ^4.4.2
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/hva_logo.png
    - assets/images/sponsor_logo.png